// Copyright (c) LooUQ Incorporated. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// in Seconds
#define TELEMETRY_INTERVAL             (5)


/* =================================================================================================================================
 *  Setup your WiFi and device connection string here
================================================================================================================================= */
#if NETWORK_TYPE == WIFI

//#define WIFI_SSID   "HOME-57A7-2.4"            // your network SSID (name)
//#define WIFI_PW     "TFK10901"        // your network password (use for WPA, or use as key for WEP)

#define WIFI_SSID "LOOUQ"
#define WIFI_PW "grouperT3ch"

#endif
 
/* Below is a typical connection string to the iotQi device hub,  you get this information from iotQi Setup on the device pages (the example below is not functional)
 *
 * Device IDs are a GUID made up of hexidecimal digits arranged in 5 tokens
 * The SharedAccessKey is generated by iotQi and will be a random string containing alpha-numeric characters a some special characters, usually this ends in an = character
 *
 * Example connection... yours will look like this
#define IOTQI_CONNECTION "HostName=iothub-prod-loouq.azure-devices.net;DeviceId=ba93e7bb-b2f3-42fa-a272-1c94e2389c25;SharedAccessKey=wnQr8WVBC8R43weh3Nf4sZ8cHJfvrYRfvZW+sioioZc="
*/

#define IOTQI_CONNECTION "HostName=iothub-a-prod-loouq.azure-devices.net;DeviceId=53509c51-d616-43b2-8c37-ef93674b3ec9;SharedAccessKey=waT+A6dhhH9M8Gnv4MqAgU5sQ1/ef5gJS9cOKexh/pI="
/* =================================================================================================================================
================================================================================================================================= */



